# Generated by Django 4.2.14 on 2024-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='who',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='who',
            field=models.ManyToManyField(to='Blogs.usermodelblog'),
        ),
    ]
